name: Plan and Apply Terraform code
description: Plans and deploys Terraform code

inputs:
  environment:
    description: 'The environment to deploy to'
    required: true
  tf-storage-account-name:
    required: true
    description: Storage account name
  tf-plan:
    required: true
    description: wether to plan or apply
  tf-apply:
    required: true
    description: wether to plan or apply
  deployments-root-directory:
    required: true
    description: The root directory where the deployments are stored

    
runs:
  using: composite
  steps:
    - name: Find version of Terraform to use
      working-directory: ${{ inputs.environment }}
      shell: bash
      id: tfversion
      run: |
        GET_CURRENT_TF_VERSION=$(grep required_version providers.tf | sort -u | tail -1 | cut -d= -f2- | xargs)
        echo CURRENT_TF_VERSION=$GET_CURRENT_TF_VERSION >> $GITHUB_ENV
    
    - uses: hashicorp/setup-terraform@v3
      working-directory: ${{ inputs.environment }}
      with:
          terraform_version: ${{ env.CURRENT_TF_VERSION }}
          terraform_wrapper: true

    - name: TF Format
      working-directory: ${{ inputs.environment }}
      shell: bash
      id: fmt
      run: terraform -v; terraform fmt -check -recursive
      
    - name: Terraform Init
      working-directory: ${{ inputs.environment }}
      shell: bash
      id: init
      run: >
        terraform init
        -input=false
        -backend-config="use_oidc=true"
        -backend-config="container_name=${{ inputs.environment }}"
        -backend-config="key=${{ inputs.environment }}.tfstate"
        -backend-config="storage_account_name=${{ inputs.tf-storage-account-name }}"
        -backend-config="tenant_id=${{ vars.TENANT_ID }}"
        -backend-config="subscription_id=${{ vars.SUBSCRIPTION_ID }}"
        -backend-config="client_id=${{ inputs.APP_ID }}"

    - name: Terraform Validate
      working-directory: ${{ inputs.environment }}
      shell: bash
      id: validate
      run: terraform validate
      
  
    - name: TF Plan
      working-directory: ${{ inputs.environment }}
      shell: bash
      id: tfplan
      run: |
        terraform plan -out ${{ inputs.environment }}.tfplan -lock-timeout=3000s
        sed -i -e '1s/^/```diff\n/' -e '$a```' -e 's/~/!/g' -e 's/^[ \t]*//' ${{ inputs.environment }}.tfplan
        echo "tfplan=${{ inputs.environment }}.tfplan" >> "$GITHUB_OUTPUT"

    - uses: mshick/add-pr-comment@v2
      working-directory: ${{ inputs.environment }}
      if: ${{ inputs.tf-plan }} == 'true'
      with:
        message-id: ${{ steps.tfplan.outputs.tfplan }}
        message-path: |
         ${{ inputs.environment }}.tfplan

    - name: TF Apply
      working-directory: ${{ inputs.environment }}
      if: ${{ inputs.tf-plan }} == 'true' && ${{ inputs.tf-apply }} == 'true'
      shell: bash
      id: tfapply
      run: terraform apply -lock-timeout=3000s -auto-approve